{{- if eq "claim" $.Values.storage.type }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.storage.claim.name }}
  labels:
    {{- include "pyramidAnalytics.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with $.Values.storage.claim.className }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ $.Values.storage.size }}
{{- end }}
