{{- if and .Values.unattended.enabled .Values.unattended.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: unattended-installation
stringData:
{{- include "pyramidAnalytics.unattended.json" . | nindent 2 }}
{{- end }}
