{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "postgresql.fullname" . }}-credentials
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ include "postgresql.fullname" . }}
    template:
      data:
        postgres-password: "{{ `{{ $var := .result | fromJson }}{{ $var.current_secret }}` }}"
  data:
    - secretKey: result
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefKey }}
{{- end }}
